name: CI/CD Corda Workflows
on:
  workflow_dispatch:
    push:
    paths-ignore:
      - 'clients/**'
      - 'contracts/**'
      - '.github/workflows/github-actions-pipeline-contracts.yml'
      - '.github/workflows/github-actions-pipeline-client-api.yml'
  push:
    branches: 
        - main
        - develop
        
jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request'  && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [main]
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Build gradle Workflows
        run: ./gradlew workflows:jar
      
      - name: Deploy workflows on Corda Node
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_CORDA_02 }}
          username: ubuntu
          port: 22
          key: ${{ secrets.KEYPAIR_CORDA_NETWORK_MACHINE }}
          source: "workflows/build/libs/*.jar"
          target: "~/corda/conf_nodes/shared/cordapps"
          strip_components: 3

      - name: Restart Corda Network
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_CORDA_02 }}
          username: ubuntu
          port: 22
          key: ${{ secrets.KEYPAIR_CORDA_NETWORK_MACHINE }}
          script: "docker-compose -f corda/conf_nodes/docker-compose.yml restart"

  develop:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request'  && github.ref == 'refs/heads/develop' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [develop]
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
      - name: Build gradle Workflows
        run: ./gradlew workflows:jar
      
      - name: Deploy workflows on Corda Node
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST_CORDA_01 }}
          username: ubuntu
          port: 22
          key: ${{ secrets.KEYPAIR_CORDA_NETWORK_MACHINE }}
          source: "workflows/build/libs/*.jar"
          target: "~/corda/conf_nodes/shared/cordapps"
          strip_components: 3
      
      - name: Restart Corda Network
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_CORDA_01 }}
          username: ubuntu
          port: 22
          key: ${{ secrets.KEYPAIR_CORDA_NETWORK_MACHINE }}
          script: "docker-compose -f corda/conf_nodes/docker-compose.yml restart"